// npx --yes live-server --host=0.0.0.0 --port=8080
// http://10.0.0.145:8080

const FPS = 60
const BALL_RADIUS = window.innerWidth / 16
const BALL_SPEED_DIVISOR = 7.5
const BALL_RESTITUTION = .85
const BALL_MIN_SPEED = 15
const GOAL_HEIGHT = BALL_RADIUS * 1.5
const GOAL_WIDTH = BALL_RADIUS * 4
const WALL_LENGTH = BALL_RADIUS * 5
const KEY_SIZE = BALL_RADIUS * .8
const TROPHY_SIZE = BALL_RADIUS * .8
const MAX_SPAWN_ATTEMPTS = 100000
const MIN_SPACE_FOR_SPAWN = WALL_LENGTH + BALL_RADIUS
const COOLDOWN_DURATION = 3000
const SWAP_DURATION = 20
const DOLLAR_COUNT = 5
const ENEMY_COUNT = 0

let canvas;
let ctx;
let ball = {}
let goal = {}
let cannon = {}
let puddle = {}
let wall = {}
let wallendA = {}
let wallendB = {}
let wormholeA = {}
let wormholeB = {}
let twinA = {}
let twinB = {}
let key = {}
let bonus = {}
let mystery = {}
let enemies = []
let obstacles = [cannon, puddle, wallendA, wallendB, wormholeA, wormholeB, twinA, twinB, key, bonus]
let swappableObstacles = [cannon, puddle, wallendA, wallendB, wormholeA, wormholeB, twinA, twinB]
let touch1 = { xPos: 0, yPos: 0 }
let spawnedObstacles = []
let rotatingObstacle = {}
let selectedObstacle = {}
const LETTER_SQUARE_SIZE = 50
let letterP = { char: 'p', xPos: 0, yPos: 0, originalX: 0, originalY: 0 }
let letterY = { char: 'y', xPos: 0, yPos: 0, originalX: 0, originalY: 0 }
let letterA = { char: 'a', xPos: 0, yPos: 0, originalX: 0, originalY: 0 }
let letterL = { char: 'l', xPos: 0, yPos: 0, originalX: 0, originalY: 0 }
let swappableLetters = [letterP, letterY, letterA, letterL]
let selectedLetter = null
let letterSwapAnimation = null
let areObstaclesHidden = false
let showWelcome = false
let showTitle = false
let isBallHidden = false
let hasFlung = false
let playButton = { xPos: window.innerWidth / 2, yPos: window.innerHeight * .6 }
let trophyCount = 0
let tries = 0
let isBottomEdgeEnabled = true
let camera = { xPos: 0, yPos : 0 }
let dollars = []
let isCelebration = false
let hasCelebrated = false
let hasGotTrophy = false 
let hasAddedTrophyThisCelebration = false
let isTrophyHidden = false
let trophies = []
let isTwinPassing = false
let hasTwinPassedThisFling = false
let swapAnimation = null
let isTwinAPassing = false
let isTwinBPassing = false
let crowdImg = document.createElement("IMG")
crowdImg.src = "images/crowd.png";
